//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelNepal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoom
    {
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> PriceId { get; set; }
        public Nullable<int> HostelId { get; set; }
    
        public virtual tblHostel tblHostel { get; set; }
        public virtual tblPrice tblPrice { get; set; }
    }
}
